### PR TITLE
Fix key error

### PR DESCRIPTION
**Pull request by mib1185**
@meichthys unfortunately, an typo issue got in with #4 which will be fixed in this PR.
Would be great, if you can review this and do a new release 1.3.1 with this fix.

### CODE REVIEW

**Comment by meichthys** [comment]
oof. LGTM! Thanks. Will be pushing out the new release shortly.

**Comment by meichthys** [comment]
@mib1185 Released as `v1.4.0`

**Comment by mib1185** [comment]
@meichthys could you please add a tag for this version? when this is done, I will create a PR in home-assistant to bump to this new version

**Comment by meichthys** [comment]
@mib1185 All set 👍

**Pull request merged**
